language: php

php:
    - 7.0
    - 7.1
    - 7.2

sudo: required

services:
  - docker

before_script:
    - composer install

script:
    - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml
    - make full-test

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
